# syntax = docker/dockerfile:1

# This version of the Dockerfile is used by the buildspec.yaml within the AWS environment

FROM public.ecr.aws/docker/library/node:current-alpine

EXPOSE 4000

COPY src/ codegen.ts tsconfig.json package.json package-lock.json  app/

WORKDIR /app

# Install all of the dependencies
RUN npm install

# Generate all of the Types
RUN npm run generate

# Build the app
RUN npm run build

CMD ["node", "dist/index.js"]
