# User email addresses
CREATE TABLE `userEmails` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `email` INT NOT NULL,
  `primary` BOOLEAN NOT NULL DEFAULT false,
  `confirmed` BOOLEAN NOT NULL DEFAULT false,
  `createdById` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifiedById` INT NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;

# Open invitiations for a user to collaborate on a Template or Plan
CREATE TABLE `userInvitations` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `invitedById` INT NOT NULL,
  `email` INT NOT NULL,
  `invitedToId` INT NOT NULL,
  `invitedToType` VARCHAR(10) NOT NULL,
  `createdById` INT NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifiedById` INT NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (invitedById) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb3;
