# Initial test users
INSERT INTO `users`
  (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`)
VALUES
  ('orgA.user@example.com', 'https://ror.org/01nrxwf90', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Harry', 'Potter', 'RESEARCHER'),
  ('orgB.user@example.com', 'https://ror.org/01tm6cn81', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Lucious', 'Malfoy', 'RESEARCHER'),
  ('orgA.admin@example.com', 'https://ror.org/01nrxwf90', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Alastor', 'Moody', 'ADMIN'),
  ('orgB.admin@example.com', 'https://ror.org/01tm6cn81', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Minerva', 'McGonagall', 'ADMIN'),
  ('super@example.com', 'https://ror.org/00dmfq477', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Albus', 'Dumbledore', 'SUPERADMIN');

# DMPTOOL - TASK TO CREATE AN ADMIN USER FOR EVERY PUBLISHED TEMPLATE
#           v6_migration:generate_mock_admins
#
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@colorado.edu', 'https://ror.org/02ttsq026', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Colorado Boulder Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@usu.edu', 'https://ror.org/00h6set76', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Utah State University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ornl.gov', 'https://ror.org/01qz5mb56', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Oak Ridge National Laboratory Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@vcu.edu', 'https://ror.org/02nkdxk79', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Virginia Commonwealth University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ucop.edu', 'https://ror.org/00dmfq477', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of California Office of the President Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@cmu.edu', 'https://ror.org/05x2bcf33', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Carnegie Mellon University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@bc.edu', 'https://ror.org/02n2fzt79', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Boston College Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@boisestate.edu', 'https://ror.org/02e3zdp86', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Boise State University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@wcu.edu', 'https://ror.org/010h78f45', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Western Carolina University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@griffith.edu.au', 'https://ror.org/02sc3r913', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Griffith University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@cuanschutz.edu', 'https://ror.org/03wmf1y16', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Colorado Anschutz Medical Campus Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@umassmed.edu', 'https://ror.org/0464eyp60', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Massachusetts Chan Medical School Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@www2.ucar.edu', 'https://ror.org/04zhhyn23', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University Corporation for Atmospheric Research Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@jmu.edu', 'https://ror.org/028pmsz77', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'James Madison University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@unr.edu', 'https://ror.org/01keh0577', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Nevada Reno Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ed.gov', 'https://ror.org/021adze67', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of Education Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@columbia.edu', 'https://ror.org/00hj8s172', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Columbia University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@usgs.gov', 'https://ror.org/035a68863', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Geological Survey Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nsf.gov', 'https://ror.org/021nxhr62', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Science Foundation Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@energy.gov', 'https://ror.org/01bj3aw27', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of Energy Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@dcc.ac.uk', 'https://ror.org/01k9d6864', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Digital Curation Centre Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nij.gov', 'https://ror.org/00v8p7w89', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Institute of Justice Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@doi.gov', 'https://ror.org/03v0pmy70', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of the Interior Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@moore.org', 'https://ror.org/006wxqw41', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Gordon and Betty Moore Foundation Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@purdue.edu', 'https://ror.org/05p8z3f47', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Purdue University System Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@noaa.gov', 'https://ror.org/02z5nhe81', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Oceanic and Atmospheric Administration Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@gulfresearchinitiative.org', 'https://ror.org/0115hrs73', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Gulf of Mexico Research Initiative Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@illinois.edu', 'https://ror.org/047426m28', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Illinois Urbana-Champaign Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@unicamp.br', 'https://ror.org/04wffgt70', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Universidade Estadual de Campinas Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@uky.edu', 'https://ror.org/02k3smh20', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Kentucky Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@arizona.edu', 'https://ror.org/03m2x1q45', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Arizona Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@fau.edu', 'https://ror.org/05p8w6387', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Florida Atlantic University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@www5.usp.br', 'https://ror.org/036rp1748', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Universidade de São Paulo Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@emory.edu', 'https://ror.org/03czfpz43', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Emory University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@fapesp.br', 'https://ror.org/02ddkpn78', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Fundação de Amparo à Pesquisa do Estado de São Paulo Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@umd.edu', 'https://ror.org/047s2c258', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Maryland, College Park Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@aus.edu', 'https://ror.org/001g2fj96', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'American University of Sharjah Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@utdallas.edu', 'https://ror.org/049emcs32', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'The University of Texas at Dallas Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@uoregon.edu', 'https://ror.org/0293rh119', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Oregon Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@hku.hk', 'https://ror.org/02zhqgq86', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Hong Kong Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@missouri.edu', 'https://ror.org/02ymw8z06', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Missouri Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@uh.edu', 'https://ror.org/048sx0r50', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Houston Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ucdenver.edu', 'https://ror.org/02hh7en24', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Colorado Denver Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@iu.edu', 'https://ror.org/01kg8sb98', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Indiana University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@twin-cities.umn.edu', 'https://ror.org/017zqws13', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Minnesota Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@duke.edu', 'https://ror.org/00py81415', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Duke University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@uwyo.edu', 'https://ror.org/01485tq96', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Wyoming Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@si.edu', 'https://ror.org/01pp8nd67', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Smithsonian Institution Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@brown.edu', 'https://ror.org/05gq02987', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Brown University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@usda.gov', 'https://ror.org/01na82s61', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of Agriculture Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@imls.gov', 'https://ror.org/030prv062', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Institute of Museum and Library Services Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@utk.edu', 'https://ror.org/020f3ap87', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Tennessee at Knoxville Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@sloan.org', 'https://ror.org/052csg198', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Alfred P. Sloan Foundation Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nist.gov', 'https://ror.org/05xpvk416', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Institute of Standards and Technology Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nasa.gov', 'https://ror.org/027ka1x80', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Aeronautics and Space Administration Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@hospitalsiriolibanes.org.br', 'https://ror.org/03r5mk904', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Hospital Sírio-Libanês Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ucdavis.edu', 'https://ror.org/05rrcem69', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of California, Davis Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@davidson.edu', 'https://ror.org/02f7k4z58', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Davidson College Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@cebrap.org.br', 'https://ror.org/01xdw4k60', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Centro Brasileiro de Análise e Planejamento Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@cuhk.edu.hk', 'https://ror.org/00t33hh48', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Chinese University of Hong Kong Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@scu.edu.au', 'https://ror.org/001xkv632', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Southern Cross University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@neh.gov', 'https://ror.org/02vdm1p28', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Endowment for the Humanities Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@iastate.edu', 'https://ror.org/04rswrd78', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Iowa State University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@psu.edu', 'https://ror.org/04p491231', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Pennsylvania State University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@hakai.org', 'https://ror.org/02pry0c91', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Hakai Institute Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@insper.edu.br', 'https://ror.org/02nmavx05', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Insper Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@faseb.org', 'https://ror.org/01mh1c318', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Federation of American Societies for Experimental Biology Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nyu.edu', 'https://ror.org/0190ak572', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'New York University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@weill.cornell.edu', 'https://ror.org/02r109517', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Weill Cornell Medicine Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@shu.edu', 'https://ror.org/007tn5k56', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Seton Hall University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ecohealthalliance.org', 'https://ror.org/02zv3m156', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'EcoHealth Alliance Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@transportation.gov', 'https://ror.org/02xfw2e90', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of Transportation Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@moorea.berkeley.edu', 'https://ror.org/04sk0et52', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Gump South Pacific Research Station Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@tetiaroasociety.org', 'https://ror.org/04p8xrf95', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Tetiaroa Society Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@stanford.edu', 'https://ror.org/00f54p054', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Stanford University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@sandia.gov', 'https://ror.org/01apwpt12', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Sandia National Laboratories Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nygenome.org', 'https://ror.org/05wf2ga96', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'New York Genome Center Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@umaryland.edu', 'https://ror.org/04rq5mt64', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Maryland, Baltimore Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@northeastern.edu', 'https://ror.org/04t5xt781', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Northeastern University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@defense.gov', 'https://ror.org/0447fe631', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'United States Department of Defense Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@wehi.edu.au', 'https://ror.org/01b6kha49', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Walter and Eliza Hall Institute of Medical Research Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@wakehealth.edu', 'https://ror.org/04v8djg66', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Atrium Health Wake Forest Baptist Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nih.gov', 'https://ror.org/01cwqze88', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'National Institutes of Health Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ufc.br', 'https://ror.org/03srtnf24', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Universidade Federal do Ceará Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@usc.edu', 'https://ror.org/03taz7m60', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Southern California Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ahrq.gov', 'https://ror.org/03jmfdf59', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Agency for Healthcare Research and Quality Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@whoi.edu', 'https://ror.org/03zbnzt98', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Woods Hole Oceanographic Institution Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@utah.edu', 'https://ror.org/03r0ha626', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Utah Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@uchc.edu', 'https://ror.org/02kzs4y22', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Connecticut Health Center Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ufabc.edu.br', 'https://ror.org/028kg9j04', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Universidade Federal do ABC Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@nymc.edu', 'https://ror.org/03dkvy735', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'New York Medical College Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@cityu.edu.hk', 'https://ror.org/03q8dnn23', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'City University of Hong Kong Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@aut.ac.nz', 'https://ror.org/01zvqw119', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Auckland University of Technology Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@umich.edu', 'https://ror.org/00jmfr291', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'University of Michigan–Ann Arbor Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@lincoln.ac.nz', 'https://ror.org/04ps1r162', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Lincoln University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@harvard.edu', 'https://ror.org/03vek6s52', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Harvard University Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@massgeneralbrigham.org', 'https://ror.org/04py2rh25', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Mass General Brigham Admin', 'Test User', 'ADMIN');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('admin@ohsu.edu', 'https://ror.org/03e62d071', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Oregon Health & Science University School of Medicine Admin', 'Test User', 'ADMIN');

# Go back and update all of the users so that they are their own creator/modifier
UPDATE users SET createdById = id, modifiedById = id;