
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 1, 'doi.org/10.48321/D12641ba82', 'SCC-IRG Track 1: Serving Households in AReas with food Insecurity with a Network for Good: SHARING', 'https://ror.org/021nxhr62', '["Munindar Singh (PI)"]', 5, '2024-02-01 16:40:10', 1, '2024-01-26 18:43:06', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'en-US' FROM projects WHERE id = 1);
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 10, 'doi.org/10.48321/D11W20', 'Um Cerrado ambientalmente sustentável e socialmente justo: termômetro das condições ambientais e de bem-estar social que coexistem no bioma', 'https://ror.org/036rp1748', '["Mayra de Freitas Preto (PI)", "María Victoria Ramos Ballester (PM)"]', 5, '2023-08-07 15:49:17', 1, '2023-08-07 15:49:17', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'pt-BR' FROM projects WHERE id = 2);
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 15, 'doi.org/10.48321/D11D16C9EB', 'EAGER: SMART-DMSP: Streamlining Metadata, Automation, and Research Tracking for Data Management and Sharing Plans', 'https://ror.org/021nxhr62', '["Sally Mae (PI)"]', 5, '2024-07-09 21:50:24', 1, '2024-07-09 21:50:24', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'en-US' FROM projects WHERE id = 3);
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 20, 'doi.org/10.48321/D136BA4701', 'Test Plan that was created in the old system', 'https://ror.org/027ka1x80', '["Tony the Tiger (PI)", "Brian Riley (PI)"]', 5, '2024-01-26 19:38:05', 1, '2024-01-26 19:38:06', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'en-US' FROM projects WHERE id = 3);
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 20, 'doi.org/10.48321/D14608', 'Spatial analysis of the vulnerability of water wells and aquifers in the Alto Tietê basin', 'https://ror.org/028kg9j04', '["Claudio Benedito Baptista Leite (PM)", "Ana Carolina Medeiros de Camargo (PI)", "Rodrigo Nehara Moreira (PI)", "Vitor Vieira Vasconcelos (PM)"]', 5, '2023-08-07 15:51:47', 1, '2023-08-07 15:51:47', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'en-US' FROM projects WHERE id = 4);
INSERT INTO projectPlans (projectId, versionedTemplateId, dmpId, title, funder, contributors, lastUpdatedById, lastUpdated, registeredById, registered, visibility, status, createdById, created, modifiedById, modified, languageId)
  (SELECT projects.id, 5, 'doi.org/10.48321/D1DS3R', 'EVALUATION OF THE EFFECT OF HETEROTYPIC SIGNALING ON TUMOR PHENOTYPE MODULATION IN MELANOMA', 'https://ror.org/02k5swt12', '["André Zelanis (DC)", "Uilla Barcick (PI)"]', 5, '2023-08-07 15:44:42', 1, '2023-08-07 15:44:42', 'PUBLIC', 'PUBLISHED', projects.id, CURDATE(), projects.id, CURDATE(), 'en-US' FROM projects WHERE id = 4);
