
ALTER TABLE affiliations
  ADD COLUMN apiTarget VARCHAR(255) NULL,
  ADD COLUMN apiAuthTarget VARCHAR(255) NULL,
  ADD COLUMN apiAuthClientId VARCHAR(255) NULL,
  ADD COLUMN apiAuthClientSecret VARCHAR(255) NULL;
