CREATE TABLE IF NOT EXISTS `planFundings` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `planId` INT UNSIGNED NOT NULL,
  `projectFundingId` INT UNSIGNED NOT NULL,
  `createdById` INT UNSIGNED NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifiedById` INT UNSIGNED NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `projectFundings` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `projectId` INT UNSIGNED NOT NULL,
  `affiliationId` VARCHAR(255) NOT NULL,
  `status` VARCHAR(16) NOT NULL,
  `funderProjectNumber` VARCHAR(255),
  `grantId` VARCHAR(255),
  `funderOpportunityNumber` VARCHAR(255),
  `createdById` INT UNSIGNED NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifiedById` INT UNSIGNED NOT NULL,
  `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;

ALTER TABLE planFundings
  ADD FOREIGN KEY (createdById) REFERENCES users(id),
  ADD FOREIGN KEY (modifiedById) REFERENCES users(id),
  ADD FOREIGN KEY (planId) REFERENCES plans(id) ON DELETE CASCADE,
  ADD FOREIGN KEY (projectFundingId) REFERENCES projectFundings(id);

ALTER TABLE projectFundings
  ADD FOREIGN KEY (createdById) REFERENCES users(id),
  ADD FOREIGN KEY (modifiedById) REFERENCES users(id),
  ADD FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE,
  ADD FOREIGN KEY (affiliationId) REFERENCES affiliations(uri);
