
# Add some researcher users
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('researcher@ucop.edu', 'https://ror.org/00dmfq477', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Jane', 'Doe', 'RESEARCHER');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('researcher@ucdavis.edu', 'https://ror.org/05rrcem69', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Jacques', 'Cousteau', 'RESEARCHER');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('researcher@stanford.edu', 'https://ror.org/00f54p054', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'Roald', 'Amundsen', 'RESEARCHER');
INSERT INTO `users` (`email`, `affiliationId`, `password`, `givenName`, `surName`, `role`) VALUES ('researcher@nyu.edu', 'https://ror.org/0190ak572', '$2a$10$f3wCBdUVt/2aMcPOb.GX1OBO9WMGxDXx5HKeSBBnrMhat4.pis4Pe', 'David', 'Livingstone', 'RESEARCHER');

# Add some research projects
INSERT INTO `projects` (`title`, `abstractText`, `researchDomainId`, `startDate`, `endDate`, `isTestProject`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations', 'Reef ecosystems are critical habitats supporting a diverse array of marine species, including eels, which play vital roles in maintaining ecological balance. This research investigates the relationship between reef ecosystems and eel populations, focusing on habitat preferences, feeding behaviors, and reproductive dynamics. By employing a combination of underwater surveys, environmental DNA (eDNA) sampling, and habitat mapping, the study aims to assess the distribution and abundance of eel species within reef environments. Additionally, the research explores the impacts of environmental stressors, such as climate change, pollution, and habitat degradation, on these populations. The findings aim to provide insights into the ecological importance of reefs for eels and inform conservation strategies to preserve these interconnected ecosystems.', (SELECT `id` from `researchDomains` WHERE `name` = 'biological-sciences'), '2025-09-01', '2028-12-31', 0, users.id, CURDATE(), users.id, CURDATE() FROM users WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projects` (`title`, `abstractText`, `researchDomainId`, `startDate`, `endDate`, `isTestProject`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice', 'The Antarctic ice sheet plays a crucial role in regulating Earths climate and sea levels. However, global warming is accelerating its melting, with profound implications for global ecosystems and human populations. This research examines the effects of rising temperatures on the ice dynamics of the South Pole, focusing on changes in ice mass, glacier flow rates, and sea ice extent. Utilizing satellite imagery, climate models, and field measurements, the study seeks to quantify the rates of ice loss and identify the primary drivers of these changes, including atmospheric warming, oceanic heat influx, and feedback loops. The project also evaluates the global consequences of Antarctic ice melt, such as sea level rise and disruptions to ocean circulation patterns. By deepening our understanding of these processes, this research aims to provide critical data for predicting future climate scenarios and informing global mitigation and adaptation strategies.', (SELECT `id` from `researchDomains` WHERE `name` = 'earth-and-environmental-sciences'), '2025-03-01', '2027-12-31', 0, users.id, CURDATE(), users.id, CURDATE() FROM users WHERE `email` = 'researcher@stanford.edu');
INSERT INTO `projects` (`title`, `abstractText`, `researchDomainId`, `startDate`, `endDate`, `isTestProject`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT 'Buzzing Boundaries: Assessing the Impact of Tsetse Fly Activity at the Source of the Nile River', 'The tsetse fly, a vector for trypanosomiasis (sleeping sickness), poses significant ecological and socio-economic challenges in sub-Saharan Africa. This research focuses on the effects of tsetse fly activity at the source of the Nile River, a critical ecological and cultural region. Through field surveys, spatial mapping, and analysis of environmental conditions, the study examines the relationship between tsetse fly populations and the local ecosystem, including impacts on biodiversity, livestock health, and human communities. Additionally, the project investigates the influence of climate and land-use changes on tsetse fly distribution and behavior. By integrating ecological and epidemiological data, this research aims to provide actionable insights for controlling tsetse populations and mitigating their effects, contributing to sustainable development and health initiatives in the region.', (SELECT `id` from `researchDomains` WHERE `name` = 'biological-sciences'), '2024-10-01', '2026-12-31', 0, users.id, CURDATE(), users.id, CURDATE() FROM users WHERE `email` = 'researcher@nyu.edu');
INSERT INTO `projects` (`title`, `abstractText`, `researchDomainId`, `startDate`, `endDate`, `isTestProject`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee', 'Algal blooms are a growing environmental concern globally, impacting freshwater ecosystems, water quality, and biodiversity. This study investigates the occurrence and effects of algal blooms on the River Lee in Cork, Ireland. By integrating field sampling, water quality analysis, and remote sensing data, this research examines the physical, chemical, and biological factors contributing to bloom formation. The study also evaluates the ecological consequences of algal blooms, including oxygen depletion, nutrient cycling disruptions, and impacts on aquatic species. Additionally, the research assesses the socio-economic implications, such as effects on water supply and recreational use. This project aims to provide actionable insights for policymakers and stakeholders to develop sustainable strategies for mitigating the effects of algal blooms and protecting the ecological integrity of the River Lee.', (SELECT `id` from `researchDomains` WHERE `name` = 'earth-and-environmental-sciences'), '2025-03-01', '2027-12-31', 0, users.id, CURDATE(), users.id, CURDATE() FROM users WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projects` (`title`, `abstractText`, `researchDomainId`, `startDate`, `endDate`, `isTestProject`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef', 'The Great Barrier Reef, the worlds largest coral reef system, is facing an unprecedented threat from coral bleaching driven by rising sea temperatures and environmental stressors. This research examines the extent, causes, and consequences of coral bleaching events within the reef ecosystem. Using remote sensing, field surveys, and water quality analysis, the study evaluates the role of factors such as thermal stress, ocean acidification, and pollution in triggering bleaching. Additionally, the project explores the ecological impacts of bleaching on reef biodiversity, fish populations, and ecosystem services. By identifying resilient coral species and analyzing the effectiveness of current mitigation strategies, this research aims to inform conservation policies and support the development of adaptive measures to protect the Great Barrier Reef in the face of climate change.', (SELECT `id` from `researchDomains` WHERE `name` = 'biological-sciences'), '2023-01-01', '2024-12-31', 0, users.id, CURDATE(), users.id, CURDATE() FROM users WHERE `email` = 'researcher@ucdavis.edu');

# Add project contributors
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'), 'https://ror.org/05rrcem69', `users`.`id`, 'Jacques', 'Cousteau', '0000-JACQ-0000-0000', 'researcher@ucdavis.edu', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'), 'https://ror.org/05rrcem69', `users`.`id`, 'Captain', 'Nemo', '0000-NEMO-0000-0000', NULL, `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'), 'https://ror.org/00f54p054', `users`.`id`, 'Roald', 'Amundsen', '0000-ROAL-0000-0000', 'researcher@stanford.edu',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@stanford.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'), 'https://ror.org/00f54p054', `users`.`id`, 'Ernest', 'Shackelton', NULL, NULL, `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@stanford.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'), 'https://ror.org/00f54p054', `users`.`id`, NULL, NULL, NULL, 'some.else@example.com', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@stanford.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Buzzing Boundaries: Assessing the Impact of Tsetse Fly Activity at the Source of the Nile River'), 'https://ror.org/0190ak572', `users`.`id`, 'David', 'Livingston', '0000-DAVI-0000-0000', 'researcher@nyu.edu',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@nyu.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee'), 'https://ror.org/05rrcem69', `users`.`id`, 'Jane', 'Doe', '0000-JANE-0000-0000', 'researcher@ucop.edu', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'), 'https://ror.org/05rrcem69', `users`.`id`, 'Jane', 'Doe', '0000-JANE-0000-0000', 'researcher@ucop.edu', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'), 'https://ror.org/05rrcem69', `users`.`id`, 'Jacques', 'Cousteau', '0000-JACQ-0000-0000', 'researcher@ucdavis.edu', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projectContributors` (`projectId`, `affiliationId`, `userId`,`givenName`, `surName`, `orcid`, `email`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'), 'https://ror.org/05rrcem69', `users`.`id`, 'Captain', 'Nemo', '0000-NEMO-0000-0000', NULL, `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');

# Add project contributor roles
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 2, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucdavis.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 3, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucdavis.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 2, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `orcid` = '0000-NEMO-0000-0000' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 2, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@stanford.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 4, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `surName` = 'Shackelton' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 1, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'some.else@example.com' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Melting Frontiers: Investigating the Effects of Global Warming on Antarctic Ice'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 2, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@nyu.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Buzzing Boundaries: Assessing the Impact of Tsetse Fly Activity at the Source of the Nile River'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 1, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucop.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 4, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucop.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 1, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucop.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 1, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `email` = 'researcher@ucdavis.edu' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 3, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `orcid` = '0000-NEMO-0000-0000' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'));
INSERT INTO `projectContributorRoles` (`projectContributorId`, `ContributorRoleId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT `id`, 4, `createdById`, CURDATE(), `createdById`, CURDATE() FROM `projectContributors` WHERE `orcid` = '0000-NEMO-0000-0000' AND `projectId` = (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'));

# Add some project funders
INSERT INTO `projectFunders` (`projectId`, `affiliationId`, `status`, `funderProjectNumber`, `grantId`, `funderOpportunityNumber`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'), 'https://ror.org/021nxhr62', 'PLANNED', NULL, NULL, 'NSF-12345-ABC',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectFunders` (`projectId`, `affiliationId`, `status`, `funderProjectNumber`, `grantId`, `funderOpportunityNumber`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee'), 'https://ror.org/051xex213', 'GRANTED', 'IRL-000000X1', 'https://example.com/awards/IRL-000000X1', NULL,`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projectFunders` (`projectId`, `affiliationId`, `status`, `funderProjectNumber`, `grantId`, `funderOpportunityNumber`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Blooms and Busts: Ecological and Environmental Effects of Algal Growth in the River Lee'), 'https://ror.org/021nxhr62', 'DENIED', NULL, NULL, 'NSF-123455678/wf34f',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucop.edu');
INSERT INTO `projectFunders` (`projectId`, `affiliationId`, `status`, `funderProjectNumber`, `grantId`, `funderOpportunityNumber`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Buzzing Boundaries: Assessing the Impact of Tsetse Fly Activity at the Source of the Nile River'), 'https://ror.org/01cwqze88', 'PLANNED', NULL, NULL, '98765TST',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@nyu.edu');
INSERT INTO `projectFunders` (`projectId`, `affiliationId`, `status`, `funderProjectNumber`, `grantId`, `funderOpportunityNumber`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Fading Reefs: Investigating Coral Bleaching at the Great Barrier Reef'), 'https://ror.org/021nxhr62', 'GRANTED', '945tg9h4g045g', 'https://awards.example.com/245t24g4tg', 'NSF-12345-ABC',`users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');

# Add a couple of research outputs with metadata standards and repositories
INSERT INTO `projectOutputs` (`projectId`, `outputTypeId`, `title`, `description`, `mayContainSensitiveInformation`, `mayContainPII`, `initialAccessLevel`, `initialLicenseId`, `anticipatedReleaseDate`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'), (SELECT `id` FROM `outputTypes` WHERE `name` = 'dataset'), 'Anguilla anguilla observations', 'Observations of the common European eel population within the reef', 0, 0, 'UNRESTRICTED', (SELECT `id` FROM `licenses` WHERE `name` = 'CC-BY-1.0'), '2025-07-01', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectOutputs` (`projectId`, `outputTypeId`, `title`, `description`, `mayContainSensitiveInformation`, `mayContainPII`, `initialAccessLevel`, `initialLicenseId`, `anticipatedReleaseDate`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projects` WHERE `title` = 'Reef Havens: Exploring the Role of Reef Ecosystems in Sustaining Eel Populations'), (SELECT `id` FROM `outputTypes` WHERE `name` = 'audiovisual'), 'Gymnothorax javanicus time-lapse series', 'Time lapse coverage of giant moray eels', 0, 0, 'UNRESTRICTED', (SELECT `id` FROM `licenses` WHERE `name` = 'CC-BY-1.0'), '2025-07-01', `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');

INSERT INTO `projectOutputMetadataStandards` (`projectOutputId`, `metadataStandardId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Anguilla anguilla observations'), (SELECT `id` FROM `metadataStandards` WHERE `name` = 'Dublin Core'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectOutputMetadataStandards` (`projectOutputId`, `metadataStandardId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Gymnothorax javanicus time-lapse series'), (SELECT `id` FROM `metadataStandards` WHERE `name` = 'Dublin Core'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectOutputMetadataStandards` (`projectOutputId`, `metadataStandardId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Gymnothorax javanicus time-lapse series'), (SELECT `id` FROM `metadataStandards` WHERE `name` = 'Marine Community Profile'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');

INSERT INTO `projectOutputRepositories` (`projectOutputId`, `repositoryId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Anguilla anguilla observations'), (SELECT `id` FROM `repositories` WHERE `name` = 'Zenodo'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectOutputRepositories` (`projectOutputId`, `repositoryId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Anguilla anguilla observations'), (SELECT `id` FROM `repositories` WHERE `name` = 'NSF Arctic Data Center'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
INSERT INTO `projectOutputRepositories` (`projectOutputId`, `repositoryId`, `createdById`, `created`, `modifiedById`, `modified`) (SELECT (SELECT `id` FROM `projectOutputs` WHERE `title` = 'Gymnothorax javanicus time-lapse series'), (SELECT `id` FROM `repositories` WHERE `name` = 'Zenodo'), `users`.`id`, CURDATE(), `users`.`id`, CURDATE() FROM `users` WHERE `email` = 'researcher@ucdavis.edu');
