import responseCachePlugin from '@apollo/server-plugin-response-cache'
import { createHash } from 'crypto'

// This plugin is used to cache responses from the GraphQL server
// The cache key is used to store the response in the cache
// The cache key is generated by concatenating the operation name and the SHA256 hash of the key data
function sha(str: string) {
  return createHash('sha256').update(str).digest('hex')
}

export default responseCachePlugin({
  generateCacheKey(rc, keyData) {
    const operationName = rc.request.operationName ?? 'unnamed'
    const key = operationName + ':' + sha(JSON.stringify(keyData))
    return key
  },
});
